{
 "title": "Endlessh Snappy",
 "description": "Dashboard for endlessh (Fix current connections)",
 "tags": [ "prometheus" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(endlessh_client_open_count_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unique IPs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(increase(endlessh_client_trapped_time_seconds[$__range]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(endlessh_sent_bytes_total[$__range]))",
     "legendFormat": "Bytes sent by endlessh"
    }
   ]
  },
  {
   "title": "Concurrent Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Connections by country",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(country) (increase(endlessh_client_open_count_total[$__range]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trapped Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(endlessh_trapped_time_seconds_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(country) (endlessh_client_open_count_total) - endlessh_client_closed_count_total",
     "legendFormat": "Open Connections"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(ip, country) (increase(endlessh_client_trapped_time_seconds[$__range]) + on(ip) group_left(country) endlessh_client_open_count * 0)",
     "legendFormat": "__auto"
    },
    { "expr": "endlessh_client_last_seen", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Locations",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    { "panelId": 32 }
   ]
  }
 ]
}